language: cpp

compiler:
 - clang
 - gcc

before_install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 # TODO - upgrade compilers
 - sudo apt-get update -qq

install:
 - sudo apt-get -qq install boost1.55 g++ gcc

before_script:
 - make test

script:
 - make sizes /usr/include/boost/variant.hpp